# -*- coding: utf-8 -*-
"""
Created on Mon Dec 16 08:24:29 2019

@author: iant


"""

# Import libraries
import requests
import urllib.request
import time
from bs4 import BeautifulSoup

# Set the URL you want to webscrape from
url = 'https://en.wikipedia.org/wiki/List_of_MPs_elected_in_the_2019_United_Kingdom_general_election'

# Connect to the URL
response = requests.get(url)

# Parse HTML and save to BeautifulSoup object¶
soup = BeautifulSoup(response.text, "html.parser")

## To download the whole data set, let's do a for loop through all a tags
#for i in range(36,len(soup.findAll('a'))+1): #'a' tags are for links
#    one_a_tag = soup.findAll('a')[i]
#    link = one_a_tag['href']
#    download_url = 'http://web.mta.info/developers/'+ link
#    urllib.request.urlretrieve(download_url,'./'+link[link.find('/turnstile_')+1:]) 
#    time.sleep(1) #pause the code for a sec


constituency_names = [
"Aberavon",
"Aberconwy",
"Aberdeen North",
"Aberdeen South",
"Airdrie and Shotts",
"Aldershot",
"Aldridge-Brownhills",
"Altrincham and Sale West",
"Alyn and Deeside",
"Amber Valley",
"Angus",
"Arfon",
"Argyll and Bute",
"Arundel and South Downs",
"Ashfield",
"Ashford",
"Ashton-under-Lyne",
"Aylesbury",
"Ayr, Carrick and Cumnock",
"Banbury",
"Banff and Buchan",
"Barking",
"Barnsley Central",
"Barnsley East",
"Barrow and Furness",
"Basildon and Billericay",
"Basingstoke",
"Bassetlaw",
"Bath",
"Batley and Spen",
"Battersea",
"Beaconsfield",
"Beckenham",
"Bedford",
#"Belfast East",
#"Belfast North",
#"Belfast South",
#"Belfast West",
"Bermondsey and Old Southwark",
"Berwick-upon-Tweed",
"Berwickshire, Roxburgh and Selkirk",
"Bethnal Green and Bow",
"Beverley and Holderness",
"Bexhill and Battle",
"Bexleyheath and Crayford",
"Birkenhead",
"Birmingham Edgbaston",
"Birmingham Erdington",
"Birmingham Hall Green",
"Birmingham Hodge Hill",
"Birmingham Ladywood",
"Birmingham Northfield",
"Birmingham Perry Barr",
"Birmingham Selly Oak",
"Birmingham Yardley",
"Bishop Auckland",
"Blackburn",
"Blackley and Broughton",
"Blackpool North and Cleveleys",
"Blackpool South",
"Blaenau Gwent",
"Blaydon",
"Blyth Valley",
"Bognor Regis and Littlehampton",
"Bolsover",
"Bolton North East",
"Bolton South East",
"Bolton West",
"Bootle",
"Boston and Skegness",
"Bosworth",
"Bournemouth East",
"Bournemouth West",
"Bracknell",
"Bradford East",
"Bradford South",
"Bradford West",
"Braintree",
"Brecon and Radnorshire",
"Brent Central",
"Brent North",
"Brentford and Isleworth",
"Brentwood and Ongar",
"Bridgend",
"Bridgwater and West Somerset",
"Brigg and Goole",
"Brighton Kemptown",
"Brighton Pavilion",
"Bristol East",
"Bristol North West",
"Bristol South",
"Bristol West",
"Broadland",
"Bromley and Chislehurst",
"Bromsgrove",
"Broxbourne",
"Broxtowe",
"Buckingham",
"Burnley",
"Burton",
"Bury North",
"Bury South",
"Bury St Edmunds",
"Caerphilly",
"Caithness, Sutherland and Easter Ross",
"Calder Valley",
"Camberwell and Peckham",
"Camborne and Redruth",
"Cambridge",
"Cannock Chase",
"Canterbury",
"Cardiff Central",
"Cardiff North",
"Cardiff South and Penarth",
"Cardiff West",
"Carlisle",
"Carmarthen East and Dinefwr",
"Carmarthen West and South Pembrokeshire",
"Carshalton and Wallington",
"Castle Point",
"Central Ayrshire",
"Central Devon",
"Central Suffolk and North Ipswich",
"Ceredigion",
"Charnwood",
"Chatham and Aylesford",
"Cheadle",
"Chelmsford",
"Chelsea and Fulham",
"Cheltenham",
"Chesham and Amersham",
"Chesterfield",
"Chichester",
"Chingford and Woodford Green",
"Chippenham",
"Chipping Barnet",
"Chorley",
"Christchurch",
"Cities of London and Westminster",
"City of Chester",
"City of Durham",
"Clacton",
"Cleethorpes",
"Clwyd South",
"Clwyd West",
"Coatbridge, Chryston and Bellshill",
"Colchester",
"Colne Valley",
"Congleton",
"Copeland",
"Corby",
"Coventry North East",
"Coventry North West",
"Coventry South",
"Crawley",
"Crewe and Nantwich",
"Croydon Central",
"Croydon North",
"Croydon South",
"Cumbernauld, Kilsyth and Kirkintilloch East",
"Cynon Valley",
"Dagenham and Rainham",
"Darlington",
"Dartford",
"Daventry",
"Delyn",
"Denton and Reddish",
"Derby North",
"Derby South",
"Derbyshire Dales",
"Devizes",
"Dewsbury",
"Don Valley",
"Doncaster Central",
"Doncaster North",
"Dover",
"Dudley North",
"Dudley South",
"Dulwich and West Norwood",
"Dumfries and Galloway",
"Dumfriesshire, Clydesdale and Tweeddale",
"Dundee East",
"Dundee West",
"Dunfermline and West Fife",
"Dwyfor Meirionnydd",
"Ealing Central and Acton",
"Ealing North",
"Ealing Southall",
"Easington",
#"East Antrim",
"East Devon",
"East Dunbartonshire",
"East Ham",
"East Hampshire",
"East Kilbride, Strathaven and Lesmahagow",
#"East Londonderry",
"East Lothian",
"East Renfrewshire",
"East Surrey",
"East Worthing and Shoreham",
"East Yorkshire",
"Eastbourne",
"Eastleigh",
"Eddisbury",
"Edinburgh East",
"Edinburgh North and Leith",
"Edinburgh South",
"Edinburgh South West",
"Edinburgh West",
"Edmonton",
"Ellesmere Port and Neston",
"Elmet and Rothwell",
"Eltham",
"Enfield North",
"Enfield Southgate",
"Epping Forest",
"Epsom and Ewell",
"Erewash",
"Erith and Thamesmead",
"Esher and Walton",
"Exeter",
"Falkirk",
"Fareham",
"Faversham and Mid Kent",
"Feltham and Heston",
#"Fermanagh and South Tyrone",
"Filton and Bradley Stoke",
"Finchley and Golders Green",
"Folkestone and Hythe",
"Forest of Dean",
#"Foyle",
"Fylde",
"Gainsborough",
"Garston and Halewood",
"Gateshead",
"Gedling",
"Gillingham and Rainham",
"Glasgow Central",
"Glasgow East",
"Glasgow North",
"Glasgow North East",
"Glasgow North West",
"Glasgow South",
"Glasgow South West",
"Glenrothes",
"Gloucester",
"Gordon",
"Gosport",
"Gower",
"Grantham and Stamford",
"Gravesham",
"Great Grimsby",
"Great Yarmouth",
"Greenwich and Woolwich",
"Guildford",
"Hackney North and Stoke Newington",
"Hackney South and Shoreditch",
"Halesowen and Rowley Regis",
"Halifax",
"Haltemprice and Howden",
"Halton",
"Hammersmith",
"Hampstead and Kilburn",
"Harborough",
"Harlow",
"Harrogate and Knaresborough",
"Harrow East",
"Harrow West",
"Hartlepool",
"Harwich and North Essex",
"Hastings and Rye",
"Havant",
"Hayes and Harlington",
"Hazel Grove",
"Hemel Hempstead",
"Hemsworth",
"Hendon",
"Henley",
"Hereford and South Herefordshire",
"Hertford and Stortford",
"Hertsmere",
"Hexham",
"Heywood and Middleton",
"High Peak",
"Hitchin and Harpenden",
"Holborn and St Pancras",
"Hornchurch and Upminster",
"Hornsey and Wood Green",
"Horsham",
"Houghton and Sunderland South",
"Hove",
"Huddersfield",
"Huntingdon",
"Hyndburn",
"Ilford North",
"Ilford South",
"Inverclyde",
"Inverness, Nairn, Badenoch and Strathspey",
"Ipswich",
"Isle of Wight",
"Islington North",
"Islington South and Finsbury",
"Islwyn",
"Jarrow",
"Keighley",
"Kenilworth and Southam",
"Kensington",
"Kettering",
"Kilmarnock and Loudoun",
"Kingston and Surbiton",
"Kingston upon Hull East",
"Kingston upon Hull North",
"Kingston upon Hull West and Hessle",
"Kingswood",
"Kirkcaldy and Cowdenbeath",
"Knowsley",
#"Lagan Valley",
"Lanark and Hamilton East",
"Lancaster and Fleetwood",
"Leeds Central",
"Leeds East",
"Leeds North East",
"Leeds North West",
"Leeds West",
"Leicester East",
"Leicester South",
"Leicester West",
"Leigh",
"Lewes",
"Lewisham East",
"Lewisham West and Penge",
"Lewisham Deptford",
"Leyton and Wanstead",
"Lichfield",
"Lincoln",
"Linlithgow and East Falkirk",
"Liverpool Riverside",
"Liverpool Walton",
"Liverpool Wavertree",
"Liverpool West Derby",
"Livingston",
"Llanelli",
"Loughborough",
"Louth and Horncastle",
"Ludlow",
"Luton North",
"Luton South",
"Macclesfield",
"Maidenhead",
"Maidstone and The Weald",
"Makerfield",
"Maldon",
"Manchester Central",
"Manchester Gorton",
"Manchester Withington",
"Mansfield",
"Meon Valley",
"Meriden",
"Merthyr Tydfil and Rhymney",
"Mid Bedfordshire",
"Mid Derbyshire",
"Mid Dorset and North Poole",
"Mid Norfolk",
"Mid Sussex",
#"Mid Ulster",
"Mid Worcestershire",
"Middlesbrough",
"Middlesbrough South and East Cleveland",
"Midlothian",
"Milton Keynes North",
"Milton Keynes South",
"Mitcham and Morden",
"Mole Valley",
"Monmouth",
"Montgomeryshire",
"Moray",
"Morecambe and Lunesdale",
"Morley and Outwood",
"Motherwell and Wishaw",
"Na h-Eileanan an Iar",
"Neath",
"New Forest East",
"New Forest West",
"Newark",
"Newbury",
"Newcastle upon Tyne Central",
"Newcastle upon Tyne East",
"Newcastle upon Tyne North",
"Newcastle-under-Lyme",
"Newport East",
"Newport West",
#"Newry and Armagh",
"Newton Abbot",
"Normanton, Pontefract and Castleford",
#"North Antrim",
"North Ayrshire and Arran",
"North Cornwall",
"North Devon",
"North Dorset",
#"North Down",
"North Durham",
"North East Bedfordshire",
"North East Cambridgeshire",
"North East Derbyshire",
"North East Fife",
"North East Hampshire",
"North East Hertfordshire",
"North East Somerset",
"North Herefordshire",
"North Norfolk",
"North Shropshire",
"North Somerset",
"North Swindon",
"North Thanet",
"North Tyneside",
"North Warwickshire",
"North West Cambridgeshire",
"North West Durham",
"North West Hampshire",
"North West Leicestershire",
"North West Norfolk",
"North Wiltshire",
"Northampton North",
"Northampton South",
"Norwich North",
"Norwich South",
"Nottingham East",
"Nottingham North",
"Nottingham South",
"Nuneaton",
"Ochil and South Perthshire",
"Ogmore",
"Old Bexley and Sidcup",
"Oldham East and Saddleworth",
"Oldham West and Royton",
"Orkney and Shetland",
"Orpington",
"Oxford East",
"Oxford West and Abingdon",
"Paisley and Renfrewshire North",
"Paisley and Renfrewshire South",
"Pendle",
"Penistone and Stocksbridge",
"Penrith and The Border",
"Perth and North Perthshire",
"Peterborough",
"Plymouth Moor View",
"Plymouth Sutton and Devonport",
"Pontypridd",
"Poole",
"Poplar and Limehouse",
"Portsmouth North",
"Portsmouth South",
"Preseli Pembrokeshire",
"Preston",
"Pudsey",
"Putney",
"Rayleigh and Wickford",
"Reading East",
"Reading West",
"Redcar",
"Redditch",
"Reigate",
"Rhondda",
"Ribble Valley",
"Richmond (Yorks)",
"Richmond Park",
"Rochdale",
"Rochester and Strood",
"Rochford and Southend East",
"Romford",
"Romsey and Southampton North",
"Ross, Skye and Lochaber",
"Rossendale and Darwen",
"Rother Valley",
"Rotherham",
"Rugby",
"Ruislip, Northwood and Pinner",
"Runnymede and Weybridge",
"Rushcliffe",
"Rutherglen and Hamilton West",
"Rutland and Melton",
"Saffron Walden",
"Salford and Eccles",
"Salisbury",
"Scarborough and Whitby",
"Scunthorpe",
"Sedgefield",
"Sefton Central",
"Selby and Ainsty",
"Sevenoaks",
"Sheffield Central",
"Sheffield South East",
"Sheffield Brightside and Hillsborough",
"Sheffield Hallam",
"Sheffield Heeley",
"Sherwood",
"Shipley",
"Shrewsbury and Atcham",
"Sittingbourne and Sheppey",
"Skipton and Ripon",
"Sleaford and North Hykeham",
"Slough",
"Solihull",
"Somerton and Frome",
#"South Antrim",
"South Basildon and East Thurrock",
"South Cambridgeshire",
"South Derbyshire",
"South Dorset",
#"South Down",
"South East Cambridgeshire",
"South East Cornwall",
"South Holland and The Deepings",
"South Leicestershire",
"South Norfolk",
"South Northamptonshire",
"South Ribble",
"South Shields",
"South Staffordshire",
"South Suffolk",
"South Swindon",
"South Thanet",
"South West Bedfordshire",
"South West Devon",
"South West Hertfordshire",
"South West Norfolk",
"South West Surrey",
"South West Wiltshire",
"Southampton Itchen",
"Southampton Test",
"Southend West",
"Southport",
"Spelthorne",
"St Albans",
"St Austell and Newquay",
"St Helens North",
"St Helens South and Whiston",
"St Ives",
"Stafford",
"Staffordshire Moorlands",
"Stalybridge and Hyde",
"Stevenage",
"Stirling",
"Stockport",
"Stockton North",
"Stockton South",
"Stoke-on-Trent Central",
"Stoke-on-Trent North",
"Stoke-on-Trent South",
"Stone",
"Stourbridge",
#"Strangford",
"Stratford-on-Avon",
"Streatham",
"Stretford and Urmston",
"Stroud",
"Suffolk Coastal",
"Sunderland Central",
"Surrey Heath",
"Sutton and Cheam",
"Sutton Coldfield",
"Swansea East",
"Swansea West",
"Tamworth",
"Tatton",
"Taunton Deane",
"Telford",
"Tewkesbury",
"The Cotswolds",
"The Wrekin",
"Thirsk and Malton",
"Thornbury and Yate",
"Thurrock",
"Tiverton and Honiton",
"Tonbridge and Malling",
"Tooting",
"Torbay",
"Torfaen",
"Torridge and West Devon",
"Totnes",
"Tottenham",
"Truro and Falmouth",
"Tunbridge Wells",
"Twickenham",
"Tynemouth",
#"Upper Bann",
"Uxbridge and South Ruislip",
"Vale of Clwyd",
"Vale of Glamorgan",
"Vauxhall",
"Wakefield",
"Wallasey",
"Walsall North",
"Walsall South",
"Walthamstow",
"Wansbeck",
"Wantage",
"Warley",
"Warrington North",
"Warrington South",
"Warwick and Leamington",
"Washington and Sunderland West",
"Watford",
"Waveney",
"Wealden",
"Weaver Vale",
"Wellingborough",
"Wells",
"Welwyn Hatfield",
"Wentworth and Dearne",
"West Aberdeenshire and Kincardine",
"West Bromwich East",
"West Bromwich West",
"West Dorset",
"West Dunbartonshire",
"West Ham",
"West Lancashire",
"West Suffolk",
#"West Tyrone",
"West Worcestershire",
"Westminster North",
"Westmorland and Lonsdale",
"Weston-Super-Mare",
"Wigan",
"Wimbledon",
"Winchester",
"Windsor",
"Wirral South",
"Wirral West",
"Witham",
"Witney",
"Woking",
"Wokingham",
"Wolverhampton North East",
"Wolverhampton South East",
"Wolverhampton South West",
"Worcester",
"Workington",
"Worsley and Eccles South",
"Worthing West",
"Wrexham",
"Wycombe",
"Wyre and Preston North",
"Wyre Forest",
"Wythenshawe and Sale East",
"Yeovil",
"Ynys Môn",
"York Central",
"York Outer",
]





party_groups = {
"LAB":["Labour", "Labour Co-op"],
"CON":["Conservative", "Conservative and Unionist Party"],
"BXP":["Brexit Party"],
"UKI":["UKIP"],
"PLD":["Plaid Cymru"],
"LIB":["Liberal Democrats", "Liberal"],
#"IND":["Independent"],
"CUK":["Change UK – TIG"],
"GRN":["Green", "Scottish Green", "Greens"],
"SNP":["SNP"],
}

votes = {"LAB":[], "CON":[], "BXP":[], "UKI":[], "PLD":[], "LIB":[], "IND":[], "CUK":[], "GRN":[], "SNP":[]}


constituencies = {}
for link in soup.find_all('a'):
    constituency = link.text
    
    if constituency in constituency_names:
#        print(link.text)
        
        constituencies[constituency] = {}
        
        con_link = link['href']
        download_url = "https://en.wikipedia.org/" + con_link
        response = requests.get(download_url)

        soup2 = BeautifulSoup(response.text, "html.parser")
        tables = soup2.body.find_all('table')
        
        for table in tables:
            for caption in table.find_all("caption"):

                for a in caption.find_all("a"):

                    if "2019" in a.text:
                        trs = table.find_all("tr")
                        
                        for tr in trs[1:]:
                            tds = tr.find_all("td")
                                
                            headers = tr.find_all("th")
                            if len(headers) == 0:
                            
                                party = tds[1].text.strip()
                                
                                votes_text = tds[3].text.strip()
                                if votes_text != "":
                                    if "," in votes_text:
                                        votes_text = votes_text.replace(",", "")
                                    if "." in votes_text:
                                        votes_text = votes_text.replace(".", "")
                                    
                                    vote_value = int(votes_text)
                                    constituencies[constituency][party] = vote_value



for party_abrev, party_group_list in party_groups.items(): #loop through short names
    for constituency, parties in constituencies.items(): #loop through constit voter data
        found = False
        for party, vote_values in parties.items():
            if party in party_group_list:
                votes[party_abrev].append(vote_values)
                found = True
        if not found:
            votes[party_abrev].append(0)


lines = []
for i in range(len(votes["LAB"])):
    rem_list = ["LAB", "LIB", "PLD", "CUK", "GRN", "SNP"]
    bre_list = ["CON", "BXP", "UKI"]
    rem = 0
    for rem_name in rem_list:
        rem += votes[rem_name][i]
        
    bre = 0
    for bre_name in bre_list:
        bre += votes[bre_name][i]
        
    if rem > 0 and bre > 0:
        
        line = "%s; %i; %i; %0.1f; %0.1f\n" %(constituency_names[i], rem, bre, (100.0*rem/(rem+bre)), (100.0*bre/(rem+bre)))
        lines.append(line)
    
    
with open("scrape.txt", "w") as f:
    f.writelines(lines)
    