# -*- coding: utf-8 -*-
"""
Created on Wed Sep 14 12:00:19 2022

@author: iant
"""


with open("/home/iant/reprocessing_script.sh", "w") as f:

    f.write("\n")
    f.write("#!/bin/bash\n")
    f.write("#generated by scripts.make_psa_transfer_sh_script.py\n")
    f.write("\n")

#!/bin/bash

START=2018-05-01
END=2018-07-01



python3 scripts/pipeline_log.py "Starting PSA data transfer: checking if products are waiting in ESA ingestion queue"
sleep 2
python3 scripts/transfer_psa_to_esa.py --check_queue

python3 scripts/pipeline_log.py "PSA data transfer: inserting logs in db"
sleep 2
./scripts/run_as_nomadr ./scripts/run_pipeline.py --log INFO insert_psa


python3 scripts/pipeline_log.py "PSA data transfer: copying data from $START to $END to archive"
sleep 2
cp -Ru /bira-iasb/data/SATELLITE/TRACE-GAS-ORBITER/NOMAD/psa/data_calibrated/2018/05 /bira-iasb/data/SATELLITE/TRACE-GAS-ORBITER/NOMAD/archive/psa/3.0/data_calibrated/2018/
cp -Ru /bira-iasb/data/SATELLITE/TRACE-GAS-ORBITER/NOMAD/psa/data_calibrated/2018/06 /bira-iasb/data/SATELLITE/TRACE-GAS-ORBITER/NOMAD/archive/psa/3.0/data_calibrated/2018/

python3 scripts/pipeline_log.py "PSA data transfer: transferring to ESA"
sleep 2
python3 scripts/transfer_psa_to_esa.py --transfer


python3 scripts/pipeline_log.py "PSA data transfer: done"

