# -*- coding: utf-8 -*-
"""
Created on Fri Nov 28 14:32:44 2025

@author: iant

counts_d is generated by phobos_auto_rad_cal.py
"""


import json
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter


def save_phobos_ideal_spectrum(counts_d, good_row_indices, min_spectra=10, plot=False, title=""):

    mean_shape_d = {}

    if plot:
        plt.figure()

        # mean_shape_d[order] = {}

    for good_row_index in good_row_indices:
        for order_ix, order in enumerate(counts_d.keys()):

            y_3d = counts_d[order]["y_3d"][:, good_row_index, :]
            scalars = counts_d[order]["fitted_params"][:, good_row_index, 0]  # same as y_spectral_mean
            offsets = counts_d[order]["fitted_params"][:, good_row_index, 1]

            max_val = np.max(scalars)

            # on first loop, find indices of best illuminated frame within the bin
            if order_ix == 0:
                frame_ixs = []

                min_ratio = 0.75
                while len(frame_ixs) < min_spectra:
                    frame_ixs = np.where(scalars > max_val * min_ratio)[0]
                    min_ratio -= 0.05

                print("%i frames chosen; ratio = %0.2f" % (len(frame_ixs), min_ratio + 0.05))

            raw = y_3d[frame_ixs, :]
            offset = offsets[frame_ixs]

            spectra = raw - offset[:, None]

            mean = np.mean(spectra, axis=0)

            if plot:
                plt.plot(mean, alpha=0.5, color="C%i" % order_ix)

            # smooth = savgol_filter(mean, 5, 2)
            # if plot:
            #     plt.plot(smooth, label=order, color="C%i" % order_ix)

            if order not in mean_shape_d.keys():
                mean_shape_d[int(order)] = {}
            # save unsmoothed
            mean_shape_d[int(order)][int(good_row_index)] = [float(f) for f in mean]

    if plot:
        plt.title(title)
        plt.ylim(-10, 50)
        plt.legend()

    return mean_shape_d
